# Generated by Django 5.2 on 2025-04-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('author_position', models.CharField(max_length=100, verbose_name='Должность автора')),
                ('authors_photo', models.ImageField(upload_to='contacts/quotes/', verbose_name='Фото автора')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
            },
        ),
    ]
