# Generated by Django 5.2 on 2025-04-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('text', models.CharField(max_length=500, verbose_name='Текст')),
                ('rating', models.SmallIntegerField(default=5, verbose_name='Оценка (от 1 до 5)')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('author_position', models.CharField(max_length=100, verbose_name='Должность автора')),
            ],
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='authors_photo',
            new_name='author_photo',
        ),
    ]
