# Generated by Django 5.2 on 2025-04-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_review_rename_authors_photo_quote_author_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='author_position',
            new_name='author_company',
        ),
    ]
