# Generated by Django 5.2 on 2025-05-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Обработано'),
        ),
    ]
