# Generated by Django 5.2 on 2025-05-02 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_taskexample'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexample',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Услуга'),
        ),
    ]
