# Generated by Django 5.2 on 2025-05-02 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_taskexample_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_image_small',
            field=models.BooleanField(default=False, verbose_name='Маленькое изображение?'),
        ),
        migrations.AlterField(
            model_name='taskexample',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_examples', to='services.service', verbose_name='Услуга'),
        ),
    ]
