# Generated by Django 5.2 on 2025-05-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_is_image_small_alter_taskexample_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.FileField(upload_to='services/', verbose_name='Изображение'),
        ),
    ]
