# Generated by Django 5.2 on 2025-05-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default='', max_length=255, verbose_name='Ссылка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='is_image_small',
            field=models.BooleanField(default=False, verbose_name='Маленькое изображение в списке услуг?'),
        ),
    ]
