# Generated by Django 5.2 on 2025-05-08 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_service_slug_alter_service_is_image_small'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название этапа')),
                ('label', models.TextField(verbose_name='Описание этапа')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Этап работы',
                'verbose_name_plural': 'Этапы работы',
            },
        ),
    ]
