# Generated by Django 5.2 on 2025-05-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_servicestage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestage',
            name='label',
            field=models.CharField(verbose_name='Подпись'),
        ),
    ]
