# Generated by Django 5.2 on 2025-05-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_servicestage_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_detail',
            field=models.TextField(default='', verbose_name='Описание в карточке услуги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='label',
            field=models.TextField(default='', verbose_name='Подпись в карточке услуги'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Описание в списке услуг'),
        ),
    ]
