# Generated by Django 5.2 on 2025-04-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_article_title_article_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='', upload_to='blog/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
