# Generated by Django 5.2 on 2025-05-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_image'),
        ('services', '0008_alter_servicestage_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='services',
            field=models.ManyToManyField(related_name='articles', to='services.service', verbose_name='Услуги'),
        ),
    ]
