# Generated by Django 5.2 on 2025-05-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярная'),
        ),
    ]
