# Generated by Django 5.2 on 2025-05-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='region_code',
            field=models.CharField(blank=True, help_text='Пример: "RU-SAR", "RU-BEL"', null=True, verbose_name='Код региона'),
        ),
    ]
