# Generated by Django 5.2 on 2025-05-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_article_region_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='city',
            field=models.CharField(blank=True, help_text='Пример: "Владивосток"', max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='article',
            name='map_card_label',
            field=models.CharField(blank=True, help_text='Пример: "новый стандарт урбанизма"', null=True, verbose_name='Подпись в карточке на карте'),
        ),
        migrations.AddField(
            model_name='article',
            name='square',
            field=models.CharField(blank=True, help_text='Пример: "20 тыс м2"', max_length=50, null=True, verbose_name='Площадь'),
        ),
        migrations.AddField(
            model_name='article',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год'),
        ),
    ]
