# Generated by Django 5.2 on 2025-04-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание')),
                ('description_label', models.TextField(max_length=1000, verbose_name='Подпись под описанием')),
                ('whatsapp_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на WhatsApp')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на Telegram')),
                ('vk_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на Вконтакте')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('company_full_name', models.CharField(blank=True, default='ООО "Техно Транс"', max_length=100, null=True, verbose_name='Полное наименование компании')),
                ('requisites_file', models.FileField(blank=True, null=True, upload_to='documentation/requisites/', verbose_name='Реквизиты')),
            ],
            options={
                'verbose_name': 'Информация о компании',
                'verbose_name_plural': 'Информация о компании',
            },
        ),
    ]
