# Generated by Django 5.2 on 2025-04-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='company_full_name',
        ),
    ]
