# Generated by Django 5.2 on 2025-04-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_companyinfo_company_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='requisites_file',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='address',
            field=models.CharField(default='690065, Приморский край, г. Владивосток, ул. Пушкина 91', max_length=150, verbose_name='Адрес'),
        ),
    ]
