# Generated by Django 5.2 on 2025-05-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_companyinfo_requisites_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='plan_file',
            field=models.FileField(blank=True, null=True, upload_to='home/company_info/', verbose_name='План работ'),
        ),
    ]
