# Generated by Django 5.2 on 2025-05-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_companyinfo_plan_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='necessary_data_file',
            field=models.FileField(blank=True, null=True, upload_to='home/company_info/', verbose_name='Перечень необходимых данных'),
        ),
    ]
