# Generated by Django 5.2 on 2025-05-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_companyinfo_necessary_data_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='work_hours',
            field=models.CharField(default='пн-пт 08:30–17:30', max_length=100, verbose_name='Время работы'),
        ),
    ]
