# Generated by Django 5.2 on 2025-05-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_companyinfo_work_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='privacy_policy',
            field=models.FileField(blank=True, null=True, upload_to='privacy_policy', verbose_name='Политика конфиденциальности'),
        ),
    ]
